# Generated by Django 4.2.3 on 2023-07-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='short_url',
            name='clicked',
            field=models.IntegerField(default=0),
        ),
    ]
