# Generated by Django 4.2.4 on 2023-09-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_user_reviews_review_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_reviews',
            name='review_text',
            field=models.CharField(max_length=50),
        ),
    ]
