# Generated by Django 4.2.4 on 2023-09-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_user_reviews_review_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='royalhotelmodel',
            name='average_rating',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1),
        ),
    ]
